//! Segmentation against a PDF a real word processor produced.
//!
//! Six successive attempts at the page-boundary rule shipped a silent defect,
//! and every one of them passed the unit fixtures. The fixtures were the
//! problem: they hand-build `ConvertedDocument`, so they encode what the author
//! believed `pdf_extract` emits. Real output differs in ways that decided every
//! one of those bugs -- LibreOffice draws the running header and footer FIRST
//! in the content stream, a running footer is the last thing on the page for
//! other producers, and a clause that wraps a page has the furniture sitting
//! between its two halves.
//!
//! The fixture is a synthetic contract generated by LibreOffice Writer from a
//! .docx carrying genuine `w:hdr`/`w:ftr` parts and a real PAGE field. It
//! contains no client material.

use minutes_archive_convert::{convert_bytes, SourceFormat};
use minutes_archive_core::retrieval::{normalize_converted_document, DocumentId};

const LIABILITY_WRAP: &[u8] =
    include_bytes!("../../../tests/fixtures/archive-real-pdf/liability-wrap.pdf");

#[test]
fn a_real_pdf_keeps_a_wrapped_cap_with_its_carve_out_and_furniture_out_of_the_body() {
    let converted = convert_bytes(SourceFormat::Pdf, LIABILITY_WRAP).expect("convert");
    assert!(
        converted.blocks.len() >= 2,
        "fixture must span pages to exercise the boundary; got {} block(s)",
        converted.blocks.len()
    );

    let normalized = normalize_converted_document(
        DocumentId::parse("real-liability").expect("id"),
        "Real Liability",
        LIABILITY_WRAP,
        &converted,
    )
    .expect("normalize");

    // The cap and the carve-out that limits it are one clause in the document
    // and must be one provision in the index. Severing them let the cap be
    // quoted to counsel without the exception that guts it.
    let cap = normalized
        .provisions
        .iter()
        .find(|provision| provision.text.contains("shall not be liable to the other"))
        .expect("the liability cap is indexed");
    assert!(
        cap.text
            .contains("shall not apply to a breach of the confidentiality"),
        "the carve-out was severed from the cap it limits:\n{}",
        cap.text
    );

    // Running furniture belongs to the page, not to the clause. In the body it
    // fabricates concept matches and lends the clause its sentence count.
    for provision in &normalized.provisions {
        let is_clause = provision.text.contains("shall not be liable to the other")
            || provision.text.contains("Recipient shall protect");
        if is_clause {
            assert!(
                !provision.text.contains("MASTER SERVICES AGREEMENT"),
                "the running header was welded into a clause body:\n{}",
                provision.text
            );
        }
    }

    // Every extracted line survives somewhere. Deleting furniture once erased
    // real carve-outs, so the index must never lose a line it was given.
    // A caption is stored in `heading`, not in `text`, so both count as
    // indexed -- `searchable_text` covers the pair.
    let indexed = normalized
        .provisions
        .iter()
        .map(|provision| {
            format!(
                "{} {}",
                provision.heading.as_deref().unwrap_or_default(),
                provision.text
            )
        })
        .collect::<Vec<_>>()
        .join(" ");
    for block in &converted.blocks {
        for line in block.text.lines().map(str::trim).filter(|l| !l.is_empty()) {
            assert!(
                indexed.contains(line),
                "a line the converter produced is not in the index: {line:?}"
            );
        }
    }
}

const LIST_TAIL_MERGE: &[u8] =
    include_bytes!("../../../tests/fixtures/archive-real-pdf/list-tail-merge.pdf");

/// Reproduces the open defect in #26 against real LibreOffice output.
///
/// The page ends mid-list on an unterminated item and the next page opens an
/// unrelated Assignment clause under a title-case caption that no lexical rule
/// recognises, in a document with one uniform font size -- so no word-level
/// rule can see either caption. The two clauses are indexed as one provision,
/// and a same-provision query for confidentiality and assignment returns a
/// card claiming a conjunction the document does not contain.
///
/// Ignored because it fails: this is a checked-in reproduction, not a
/// regression guard. A geometric converter was tried and reverted (see the
/// revert of 0253b6aa) -- it fixed this and silently deleted section captions
/// from documents with no running header, which is worse. The fixture and this
/// test are kept so the next attempt starts from a measured failure.
#[test]
#[ignore = "open defect #26: no structure signal exists for uniform-size, title-case captions"]
fn a_real_pdf_does_not_fabricate_a_same_provision_conjunction() {
    let converted = convert_bytes(SourceFormat::Pdf, LIST_TAIL_MERGE).expect("convert");
    let normalized = normalize_converted_document(
        DocumentId::parse("list-tail-merge").expect("id"),
        "List Tail Merge",
        LIST_TAIL_MERGE,
        &converted,
    )
    .expect("normalize");

    for provision in &normalized.provisions {
        let carries_confidentiality = provision.text.contains("Confidential Information");
        let carries_assignment = provision.text.contains("may assign");
        assert!(
            !(carries_confidentiality && carries_assignment),
            "one provision now spans two unrelated clauses:\n{}",
            provision.text
        );
    }
}
